### PR TITLE
Use correct class for pygments highlighting

### PR DESCRIPTION
**Pull request by andylolz**
`.language-python` is the wrong class, and doesn’t trigger
syntax highlighting. We should instead be using `.python`.

Refs CodeClub/lesson_format#158

### CODE REVIEW

**Comment by arve0** [comment]
Simpy adding python should be enough for pandoc to add the classes `sourceCode` and `python`:

<pre>
```python
for i in range(10):
    print(i)
```
</pre>

```sh
$ pandoc -i skilpadder.md -o skilpadder.html
$ $ ag sourceCode skilpadder.html 
19:<pre class="sourceCode python"><code class="sourceCode python"><span ....
```

Hah, too late!

**Comment by andylolz** [comment]
Haha :) Yeah – I was just caught in two minds about which was simpler for editors (since the normal pandoc syntax uses curly brackets.) This seems more markdowny than pandocy.

**Comment by andylolz** [comment]
I’m super tempted to merge this one, to see how @codeclubrobot copes with it.
@arve0: I take it this change looks good to you?
@CodeClubRik: Ping! Are you okay with me merging this one?

**Comment by arve0** [comment]
Yes, its the same syntax we use. Works really nice with highlight.js (which also support language detection, which is nice in a transitional period).

**Comment by CodeClubRik** [comment]
@andylolz no problem - feel free to merge this one! :)

**Comment by andylolz** [comment]
Thanks! (and good tip re. highlight.js!)

**Comment by andylolz** [comment]
Great – thanks, Rik!

**Comment by andylolz** [comment]
Looks [quite nice](http://codeclubrobot.github.io/CodeClubUK-Projects/en-GB/05_python/06/Compliment%20Generator.html#step-2-endless-compliments)!

**Comment by CodeClubRik** [comment]
ahhh, that looks amazing!

**Pull request merged**
