### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by minttusofia**

### CODE REVIEW

**Comment by CodeClubRik** [comment]
Thanks for this translation :)

**Comment by CodeClubRik** [comment]
I've added the images and the project resources in to the project folder, as well as a manifest:

https://github.com/CodeClub/python-curriculum/commit/5b719fb6a11ca5261d5ce76bacb5fdcde905f66a

You're welcome to translate and replace any images, etc.

**Comment by minttusofia** [comment]
Is there a simple way to translate the images?

2015-06-12 15:23 GMT+01:00 Rik <notifications@github.com>:

**Comment by CodeClubRik** [comment]
Not that I'm aware of. I think it's a case of translating the program output and creating new screenshots.

**Pull request merged**
